/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface TrickButton {

    }
  }

  interface HTMLTrickButtonElement extends StencilComponents.TrickButton, HTMLStencilElement {}

  var HTMLTrickButtonElement: {
    prototype: HTMLTrickButtonElement;
    new (): HTMLTrickButtonElement;
  };
  interface HTMLElementTagNameMap {
    'trick-button': HTMLTrickButtonElement;
  }
  interface ElementTagNameMap {
    'trick-button': HTMLTrickButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'trick-button': JSXElements.TrickButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface TrickButtonAttributes extends HTMLAttributes {
      'onButtonClicked'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface TopBar {
      'background': string;
    }
  }

  interface HTMLTopBarElement extends StencilComponents.TopBar, HTMLStencilElement {}

  var HTMLTopBarElement: {
    prototype: HTMLTopBarElement;
    new (): HTMLTopBarElement;
  };
  interface HTMLElementTagNameMap {
    'top-bar': HTMLTopBarElement;
  }
  interface ElementTagNameMap {
    'top-bar': HTMLTopBarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'top-bar': JSXElements.TopBarAttributes;
    }
  }
  namespace JSXElements {
    export interface TopBarAttributes extends HTMLAttributes {
      'background'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;